#!/usr/bin/env python3
"""Glossary picker - local web GUI.  http://localhost:8770

Reads llmPipeline/out/glossary.db directly, so it always reflects the current
state (including stage-2 candidates arriving while you work) and every pick is
persisted the moment it is made.

Three review stages:
  queue   1,400 main queue        - undecided, highest priority
  stage2  deferred frequency-1    - candidates generated by propose_deferred.py
  auto      273 auto-accepted     - confirm or override

Safety: every pick is written to the DB *and* appended to out/picks.jsonl, so a
crash or an accidental DB delete never loses a decision.
"""
from __future__ import annotations

import json
import os
import secrets
import sqlite3
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

HERE = Path(__file__).resolve().parent
DB = HERE.parent / "out" / "glossary.db"
JOURNAL = HERE.parent / "out" / "picks.jsonl"
PAGE = HERE / "static" / "picker.html"
TOKEN_FILE = HERE.parent / "out" / ".picker_token"
PORT = 8770

# Shared secret. /api/pick WRITES to the glossary, so once this is behind a public
# tunnel an unguessable URL is not sufficient protection - tunnel hostnames leak
# through referrers, logs and scanning. Token is reused across restarts so a
# phone that has the link keeps working.
if TOKEN_FILE.exists():
    TOKEN = TOKEN_FILE.read_text(encoding="utf-8").strip()
else:
    TOKEN = os.environ.get("PICKER_TOKEN") or secrets.token_urlsafe(18)
    TOKEN_FILE.parent.mkdir(parents=True, exist_ok=True)
    TOKEN_FILE.write_text(TOKEN, encoding="utf-8")

DENIED = (b"<!doctype html><meta name=viewport content='width=device-width'>"
          b"<body style='font:16px system-ui;padding:2rem'>"
          b"<h3>Not authorised</h3><p>Open the link that includes the access key.</p>")

PICKS_SCHEMA = """
CREATE TABLE IF NOT EXISTS picks (
    key         TEXT PRIMARY KEY,
    bg          TEXT,
    status      TEXT,          -- picked | skipped | flagged
    keep_latin  INTEGER DEFAULT 0,
    first_use   INTEGER DEFAULT 1,
    note        TEXT,
    stage       TEXT,
    ts          REAL
);
"""


def db() -> sqlite3.Connection:
    c = sqlite3.connect(str(DB), timeout=30)
    c.row_factory = sqlite3.Row
    c.executescript(PICKS_SCHEMA)
    return c


def _j(s, d):
    try:
        return json.loads(s) if s else d
    except Exception:  # noqa: BLE001
        return d


STAGE_SQL = {
    "queue": "p.decision = 'queue'",
    "stage2": "p.decision = 'stage2'",
    "auto": "p.decision = 'auto'",
}


def fetch_items(stage: str, category: str = "", undecided_only: bool = True,
                q: str = "", limit: int = 4000, view: str = ""):
    con = db()
    where = [STAGE_SQL.get(stage, STAGE_SQL["queue"])]
    args: list = []
    if category:
        where.append("t.category = ?")
        args.append(category)
    if q:
        where.append("t.term LIKE ?")
        args.append(f"%{q}%")

    # `view` wins over undecided_only: flagging is only useful if the flagged
    # set can be pulled back up later as a batch.
    if view in ("flagged", "skipped", "picked"):
        where.append("pk.status = ?")
        args.append(view)
    elif view == "decided":
        where.append("pk.key IS NOT NULL")
    elif undecided_only:
        where.append("pk.key IS NULL")

    rows = con.execute(f"""
        SELECT t.key, t.term, t.category, t.freq, t.contexts_json, t.existing_bg,
               t.sources_json, p.candidates_json, p.chosen, p.reason,
               pk.bg AS picked_bg, pk.status AS picked_status, pk.note AS picked_note,
               pk.keep_latin AS picked_latin, pk.first_use AS picked_first
        FROM proposals p
        JOIN terms t ON t.key = p.key
        LEFT JOIN picks pk ON pk.key = p.key
        WHERE {' AND '.join(where)}
        ORDER BY t.freq DESC, t.term
        LIMIT ?""", (*args, limit)).fetchall()

    out = []
    for r in rows:
        cands = _j(r["candidates_json"], [])
        # existing human translation always first - keeping it is one keypress
        if r["existing_bg"]:
            cands = ([{"bg": r["existing_bg"], "votes": 0, "existing": True}]
                     + [c for c in cands if c.get("bg") != r["existing_bg"]])
        if r["chosen"] and not any(c.get("bg") == r["chosen"] for c in cands):
            cands.insert(0, {"bg": r["chosen"], "votes": 5, "auto": True})
        out.append({
            "key": r["key"], "term": r["term"], "category": r["category"],
            "freq": r["freq"], "contexts": _j(r["contexts_json"], []),
            "existing_bg": r["existing_bg"], "sources": _j(r["sources_json"], []),
            "candidates": cands, "auto_bg": r["chosen"], "reason": r["reason"],
            "picked": {"bg": r["picked_bg"], "status": r["picked_status"],
                       "note": r["picked_note"], "keep_latin": r["picked_latin"],
                       "first_use": r["picked_first"]} if r["picked_status"] else None,
        })
    con.close()
    return out


def stats():
    con = db()
    s = {}
    for stage, cond in STAGE_SQL.items():
        tot = con.execute(
            f"SELECT COUNT(*) FROM proposals p WHERE {cond}").fetchone()[0]
        done = con.execute(
            f"""SELECT COUNT(*) FROM proposals p JOIN picks pk ON pk.key=p.key
                WHERE {cond}""").fetchone()[0]
        s[stage] = {"total": tot, "done": done}
    cats = [r[0] for r in con.execute(
        "SELECT DISTINCT category FROM terms WHERE category IS NOT NULL ORDER BY category")]
    by_status = dict(con.execute(
        "SELECT status, COUNT(*) FROM picks GROUP BY status").fetchall())
    con.close()
    return {"stages": s, "categories": cats, "by_status": by_status}


def save_pick(d: dict) -> None:
    con = db()
    con.execute(
        """INSERT OR REPLACE INTO picks(key,bg,status,keep_latin,first_use,note,stage,ts)
           VALUES (?,?,?,?,?,?,?,?)""",
        (d["key"], d.get("bg"), d.get("status", "picked"),
         int(bool(d.get("keep_latin"))), int(bool(d.get("first_use", True))),
         d.get("note"), d.get("stage"), time.time()))
    con.commit()
    con.close()
    # append-only journal: survives a lost or corrupted DB
    with open(JOURNAL, "a", encoding="utf-8") as fh:
        fh.write(json.dumps({**d, "ts": time.time()}, ensure_ascii=False) + "\n")


class H(BaseHTTPRequestHandler):
    def log_message(self, *a):
        pass

    # ── auth ──
    def _authed(self, qs) -> bool:
        supplied = (qs.get("k", [""])[0]
                    or self.headers.get("X-Picker-Token", "")
                    or self._cookie_token())
        return secrets.compare_digest(supplied, TOKEN)

    def _cookie_token(self) -> str:
        for part in (self.headers.get("Cookie") or "").split(";"):
            k, _, v = part.strip().partition("=")
            if k == "pk":
                return v
        return ""

    def _deny(self):
        self.send_response(401)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(DENIED)))
        self.end_headers()
        self.wfile.write(DENIED)

    def _send(self, obj, code=200):
        b = json.dumps(obj, ensure_ascii=False).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Content-Length", str(len(b)))
        self.end_headers()
        self.wfile.write(b)

    def do_GET(self):
        u = urlparse(self.path)
        qs = parse_qs(u.query)
        if not self._authed(qs):
            self._deny()
            return
        if u.path == "/api/items":
            self._send(fetch_items(
                qs.get("stage", ["queue"])[0],
                qs.get("cat", [""])[0],
                qs.get("all", ["0"])[0] != "1",
                qs.get("q", [""])[0],
                view=qs.get("view", [""])[0]))
        elif u.path == "/api/stats":
            self._send(stats())
        else:
            b = PAGE.read_bytes()
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            # set once from ?k= so the phone keeps working on plain reloads
            self.send_header(
                "Set-Cookie",
                f"pk={TOKEN}; Path=/; Max-Age=2592000; SameSite=Lax")
            self.send_header("Content-Length", str(len(b)))
            self.end_headers()
            self.wfile.write(b)

    def do_POST(self):
        u = urlparse(self.path)
        if not self._authed(parse_qs(u.query)):
            self._send({"error": "unauthorised"}, 401)
            return
        if u.path != "/api/pick":
            self._send({"error": "not found"}, 404)
            return
        n = int(self.headers.get("Content-Length", 0))
        try:
            d = json.loads(self.rfile.read(n) or b"{}")
            save_pick(d)
            self._send({"ok": True})
        except Exception as e:  # noqa: BLE001
            self._send({"error": str(e)}, 500)


if __name__ == "__main__":
    if not DB.exists():
        raise SystemExit(f"no database at {DB}")
    print(f"glossary picker: http://localhost:{PORT}/?k={TOKEN}")
    print(f"access key: {TOKEN}")
    # Threading matters behind a tunnel: a phone on a slow link holding one
    # connection would otherwise block every other request.
    ThreadingHTTPServer(("127.0.0.1", PORT), H).serve_forever()
