#!/usr/bin/env python3
"""Export the settled glossary from the working DB to a committed text snapshot.

out/glossary.db is gitignored: it is a 5.8 MB binary that changes on every pick,
so it would bloat history and never diff usefully. This writes the durable,
reviewable form that does get committed.

    python llmPipeline/export_glossary.py
"""
from __future__ import annotations

import json
import sqlite3
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
DB = HERE / "out" / "glossary.db"
JSON_OUT = HERE / "glossary_settled.json"
MD_OUT = HERE / "glossary_settled.md"


def main() -> int:
    con = sqlite3.connect(str(DB))
    rows = con.execute("""
        SELECT t.term, COALESCE(pk.bg, p.chosen) AS bg, t.category, t.freq,
               COALESCE(pk.status, 'auto') AS status, p.reason
        FROM terms t
        JOIN proposals p ON p.key = t.key
        LEFT JOIN picks pk ON pk.key = t.key
        WHERE COALESCE(pk.bg, p.chosen) IS NOT NULL
        ORDER BY t.category, t.term""").fetchall()

    data = [{"en": t, "bg": bg, "category": c or "UNCLEAR", "freq": f,
             "status": s, "reason": r} for t, bg, c, f, s, r in rows]
    JSON_OUT.write_text(json.dumps(data, ensure_ascii=False, indent=1),
                        encoding="utf-8")

    by_cat: dict[str, list] = defaultdict(list)
    for d in data:
        by_cat[d["category"]].append(d)

    md = ["# Settled glossary (generated)", "",
          f"{len(data)} terms. Generated by `llmPipeline/export_glossary.py` from the",
          "working database; edit terms in the picker, not here.", ""]
    for cat in sorted(by_cat):
        md += [f"## {cat} ({len(by_cat[cat])})", "",
               "| English | Bulgarian | freq |", "|---|---|---:|"]
        for d in sorted(by_cat[cat], key=lambda x: (-x["freq"], x["en"])):
            en = d["en"].replace("|", "\\|")
            bg = (d["bg"] or "").replace("|", "\\|")
            md.append(f"| {en} | {bg} | {d['freq']} |")
        md.append("")
    MD_OUT.write_text("\n".join(md) + "\n", encoding="utf-8")

    print(f"{len(data)} terms -> {JSON_OUT.name}, {MD_OUT.name}")
    print(f"  categories: {len(by_cat)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
